// countriesData.ts
// noinspection SpellCheckingInspection

export interface countriesDataInterface {
	name: string;
	location: [number, number];
	territories: [number, number][] | null;
	ownedLocation: [number, number] | null;
	acceptedNames: string[];
}

export const countriesData: countriesDataInterface[] = [
	{name: "Algeria", location: [0, 0], territories: null, ownedLocation: null, acceptedNames: ["algeria"]},
	{name: "Angola", location: [0, 1], territories: null, ownedLocation: null, acceptedNames: ["angola"]},
	{name: "Benin", location: [0, 2], territories: null, ownedLocation: null, acceptedNames: ["benin"]},
	{name: "Botswana", location: [0, 3], territories: null, ownedLocation: null, acceptedNames: ["botswana"]},
	{name: "Burkina Faso", location: [0, 4], territories: null, ownedLocation: null, acceptedNames: ["burkinafaso"]},
	{name: "Burundi", location: [0, 5], territories: null, ownedLocation: null, acceptedNames: ["burundi"]},
	{name: "Cameroon", location: [0, 6], territories: null, ownedLocation: null, acceptedNames: ["cameroon"]},
	{name: "Cape Verde", location: [0, 7], territories: null, ownedLocation: null, acceptedNames: ["capeverde"]},
	{name: "Central African Republic", location: [0, 8], territories: null, ownedLocation: null, acceptedNames: ["car", "centralafricanrepublic"]},
	{name: "Chad", location: [0, 9], territories: null, ownedLocation: null, acceptedNames: ["chad"]},
	{name: "Comoros", location: [0, 10], territories: null, ownedLocation: null, acceptedNames: ["comoros"]},
	{name: "Congo", location: [0, 11], territories: null, ownedLocation: null, acceptedNames: ["congo"]},
	{name: "Cote d'Ivoire", location: [0, 12], territories: null, ownedLocation: null, acceptedNames: ["ivorycoast", "coted'ivoire"]},
	{name: "Democratic Republic of the Congo", location: [0, 13], territories: null, ownedLocation: null, acceptedNames: ["drc", "congo", "democraticrepublicofthecongo"]},
	{name: "Djibouti", location: [0, 14], territories: null, ownedLocation: null, acceptedNames: ["djibouti"]},
	{name: "Egypt", location: [0, 15], territories: null, ownedLocation: null, acceptedNames: ["egypt"]},
	{name: "Equatorial Guinea", location: [0, 16], territories: null, ownedLocation: null, acceptedNames: ["equatorialguinea"]},
	{name: "Eritrea", location: [0, 17], territories: null, ownedLocation: null, acceptedNames: ["eritrea"]},
	{name: "Ethiopia", location: [0, 18], territories: null, ownedLocation: null, acceptedNames: ["ethiopia"]},
	{name: "Mayotte (FR)", location: [0, 19], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Reunion (FR)", location: [0, 20], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Gabon", location: [0, 21], territories: null, ownedLocation: null, acceptedNames: ["gabon"]},
	{name: "Gambia", location: [0, 22], territories: null, ownedLocation: null, acceptedNames: ["gambia"]},
	{name: "Ghana", location: [0, 23], territories: null, ownedLocation: null, acceptedNames: ["ghana"]},
	{name: "Guinea", location: [0, 24], territories: null, ownedLocation: null, acceptedNames: ["guinea"]},
	{name: "Guinea-Bissau", location: [0, 25], territories: null, ownedLocation: null, acceptedNames: ["guineabissau", "guinea-bissau"]},
	{name: "Kenya", location: [0, 26], territories: null, ownedLocation: null, acceptedNames: ["kenya"]},
	{name: "Lesotho", location: [0, 27], territories: null, ownedLocation: null, acceptedNames: ["lesotho"]},
	{name: "Liberia", location: [0, 28], territories: null, ownedLocation: null, acceptedNames: ["liberia"]},
	{name: "Libya", location: [0, 29], territories: null, ownedLocation: null, acceptedNames: ["libya"]},
	{name: "Madagascar", location: [0, 30], territories: null, ownedLocation: null, acceptedNames: ["madagascar"]},
	{name: "Malawi", location: [0, 31], territories: null, ownedLocation: null, acceptedNames: ["malawi"]},
	{name: "Mali", location: [0, 32], territories: null, ownedLocation: null, acceptedNames: ["mali"]},
	{name: "Mauritania", location: [0, 33], territories: null, ownedLocation: null, acceptedNames: ["mauritania"]},
	{name: "Mauritius", location: [0, 34], territories: null, ownedLocation: null, acceptedNames: ["mauritius"]},
	{name: "Morocco", location: [0, 35], territories: [[0, 53]], ownedLocation: null, acceptedNames: ["morocco"]},
	{name: "Mozambique", location: [0, 36], territories: null, ownedLocation: null, acceptedNames: ["mozambique"]},
	{name: "Namibia", location: [0, 37], territories: null, ownedLocation: null, acceptedNames: ["namibia"]},
	{name: "Niger", location: [0, 38], territories: null, ownedLocation: null, acceptedNames: ["niger"]},
	{name: "Nigeria", location: [0, 39], territories: null, ownedLocation: null, acceptedNames: ["nigeria"]},
	{name: "Rwanda", location: [0, 40], territories: null, ownedLocation: null, acceptedNames: ["rwanda"]},
	{name: "Senegal", location: [0, 41], territories: null, ownedLocation: null, acceptedNames: ["senegal"]},
	{name: "Seychelles", location: [0, 42], territories: null, ownedLocation: null, acceptedNames: ["seychelles"]},
	{name: "Sierra Leone", location: [0, 43], territories: null, ownedLocation: null, acceptedNames: ["sierraleone"]},
	{name: "Somalia", location: [0, 44], territories: null, ownedLocation: null, acceptedNames: ["somalia"]},
	{name: "South Africa", location: [0, 45], territories: null, ownedLocation: null, acceptedNames: ["rsa", "southafrica"]},
	{name: "South Sudan", location: [0, 46], territories: null, ownedLocation: null, acceptedNames: ["southsudan"]},
	{name: "Sudan", location: [0, 47], territories: null, ownedLocation: null, acceptedNames: ["sudan"]},
	{name: "Eswatini", location: [0, 48], territories: null, ownedLocation: null, acceptedNames: ["eswatini"]},
	{name: "Tanzania", location: [0, 49], territories: null, ownedLocation: null, acceptedNames: ["tanzania"]},
	{name: "Togo", location: [0, 50], territories: null, ownedLocation: null, acceptedNames: ["togo"]},
	{name: "Tunisia", location: [0, 51], territories: null, ownedLocation: null, acceptedNames: ["tunisia"]},
	{name: "Uganda", location: [0, 52], territories: null, ownedLocation: null, acceptedNames: ["uganda"]},
	{name: "Western Sahara", location: [0, 53], territories: null, ownedLocation: [0, 35], acceptedNames: []},
	{name: "Zambia", location: [0, 54], territories: null, ownedLocation: null, acceptedNames: ["zambia"]},
	{name: "Zimbabwe", location: [0, 55], territories: null, ownedLocation: null, acceptedNames: ["zimbabwe"]},
	{name: "Antigua and Barbuda", location: [1, 0], territories: null, ownedLocation: null, acceptedNames: ["antigua", "antiguaandbarbuda"]},
	{name: "Argentina", location: [1, 1], territories: null, ownedLocation: null, acceptedNames: ["argentina"]},
	{name: "Bahamas", location: [1, 2], territories: null, ownedLocation: null, acceptedNames: ["bahamas"]},
	{name: "Barbados", location: [1, 3], territories: null, ownedLocation: null, acceptedNames: ["barbados"]},
	{name: "Belize", location: [1, 4], territories: null, ownedLocation: null, acceptedNames: ["belize"]},
	{name: "Bolivia", location: [1, 5], territories: null, ownedLocation: null, acceptedNames: ["bolivia"]},
	{name: "Brazil", location: [1, 6], territories: null, ownedLocation: null, acceptedNames: ["brazil"]},
	{name: "Canada", location: [1, 7], territories: null, ownedLocation: null, acceptedNames: ["canada"]},
	{name: "Chile", location: [1, 8], territories: null, ownedLocation: null, acceptedNames: ["chile"]},
	{name: "Colombia", location: [1, 9], territories: null, ownedLocation: null, acceptedNames: ["colombia"]},
	{name: "Costa Rica", location: [1, 10], territories: null, ownedLocation: null, acceptedNames: ["costarica"]},
	{name: "Cuba", location: [1, 11], territories: null, ownedLocation: null, acceptedNames: ["cuba"]},
	{name: "Greenland (DK)", location: [1, 12], territories: null, ownedLocation: [5, 11], acceptedNames: []},
	{name: "Dominican Republic", location: [1, 13], territories: null, ownedLocation: null, acceptedNames: ["dominicanrepublic", "dr"]},
	{name: "Dominica", location: [1, 14], territories: null, ownedLocation: null, acceptedNames: ["dominica"]},
	{name: "Ecuador", location: [1, 15], territories: null, ownedLocation: null, acceptedNames: ["ecuador"]},
	{name: "Guiana (FR)", location: [1, 16], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Guadeloupe (FR)", location: [1, 17], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Martinique (FR)", location: [1, 18], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Grenada", location: [1, 19], territories: null, ownedLocation: null, acceptedNames: ["grenada"]},
	{name: "Guatemala", location: [1, 20], territories: null, ownedLocation: null, acceptedNames: ["guatemala"]},
	{name: "Guyana", location: [1, 21], territories: null, ownedLocation: null, acceptedNames: ["guyana"]},
	{name: "Haiti", location: [1, 22], territories: null, ownedLocation: null, acceptedNames: ["haiti"]},
	{name: "Honduras", location: [1, 23], territories: null, ownedLocation: null, acceptedNames: ["honduras"]},
	{name: "Jamaica", location: [1, 24], territories: null, ownedLocation: null, acceptedNames: ["jamaica"]},
	{name: "Mexico", location: [1, 25], territories: null, ownedLocation: null, acceptedNames: ["mexico"]},
	{name: "Nicaragua", location: [1, 26], territories: null, ownedLocation: null, acceptedNames: ["nicaragua"]},
	{name: "Anguilla and Sint Maarten (NT)", location: [1, 27], territories: null, ownedLocation: [5, 29], acceptedNames: []},
	{name: "Curacao (NT)", location: [1, 28], territories: null, ownedLocation: [5, 29], acceptedNames: []},
	{name: "Panama", location: [1, 29], territories: null, ownedLocation: null, acceptedNames: ["panama"]},
	{name: "Paraguay", location: [1, 30], territories: null, ownedLocation: null, acceptedNames: ["paraguay"]},
	{name: "Peru", location: [1, 31], territories: null, ownedLocation: null, acceptedNames: ["peru"]},
	{name: "Puerto Rico", location: [1, 32], territories: null, ownedLocation: [1, 45], acceptedNames: []},
	{name: "Saint Kitts and Nevis", location: [1, 33], territories: null, ownedLocation: null, acceptedNames: ["stkitts", "saintkittsandnevis"]},
	{name: "Saint Lucia", location: [1, 34], territories: null, ownedLocation: null, acceptedNames: ["stlucia", "saintlucia"]},
	{name: "Saint Vincent and the Grenadines", location: [1, 35], territories: null, ownedLocation: null, acceptedNames: ["stvincent", "saintvincentandthegrenadines"]},
	{name: "El Salvador", location: [1, 36], territories: null, ownedLocation: null, acceptedNames: ["elsalvador"]},
	{name: "Suriname", location: [1, 37], territories: null, ownedLocation: null, acceptedNames: ["suriname"]},
	{name: "Trinidad and Tobago", location: [1, 38], territories: null, ownedLocation: null, acceptedNames: ["trinidad", "trinidadandtobago"]},
	{name: "Bermuda (UK)", location: [1, 39], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Cayman Islands (UK)", location: [1, 40], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Falkland Islands (UK)", location: [1, 41], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Plymouth (UK)", location: [1, 42], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Turks and Caicos Islands (UK)", location: [1, 43], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Virgin Islands (UK)", location: [1, 44], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "United States of America", location: [1, 45], territories: [[1, 32], [1, 47], [4, 16], [4, 17]], ownedLocation: null, acceptedNames: ["usa", "unitedstatesofamerica"]},
	{name: "Uruguay", location: [1, 46], territories: null, ownedLocation: null, acceptedNames: ["uruguay"]},
	{name: "Virgin Islands (US)", location: [1, 47], territories: null, ownedLocation: [1, 45], acceptedNames: []},
	{name: "Venezuela", location: [1, 48], territories: null, ownedLocation: null, acceptedNames: ["venezuela"]},
	{name: "Antarctica", location: [2, 0], territories: null, ownedLocation: null, acceptedNames: []},
	{name: "South Georgia (UK)", location: [2, 1], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "South Sandwhich Islands (UK)", location: [2, 2], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "Afghanistan", location: [3, 0], territories: null, ownedLocation: null, acceptedNames: ["afghanistan"]},
	{name: "Armenia", location: [3, 1], territories: null, ownedLocation: null, acceptedNames: ["armenia"]},
	{name: "Azerbaijan", location: [3, 2], territories: null, ownedLocation: null, acceptedNames: ["azerbaijan"]},
	{name: "Bahrain", location: [3, 3], territories: null, ownedLocation: null, acceptedNames: ["bahrain"]},
	{name: "Bangladesh", location: [3, 4], territories: null, ownedLocation: null, acceptedNames: ["bangladesh"]},
	{name: "Bhutan", location: [3, 5], territories: null, ownedLocation: null, acceptedNames: ["bhutan"]},
	{name: "Brunei", location: [3, 6], territories: null, ownedLocation: null, acceptedNames: ["brunei"]},
	{name: "Cambodia", location: [3, 7], territories: null, ownedLocation: null, acceptedNames: ["cambodia"]},
	{name: "China", location: [3, 8], territories: null, ownedLocation: null, acceptedNames: ["proc", "china"]},
	{name: "East Timor", location: [3, 9], territories: null, ownedLocation: null, acceptedNames: ["timorleste", "easttimor"]},
	{name: "Georgia", location: [3, 10], territories: null, ownedLocation: null, acceptedNames: ["georgia"]},
	{name: "Andaman Islands (IN)", location: [3, 11], territories: null, ownedLocation: [3, 13], acceptedNames: []},
	{name: "Kashmir (IN)", location: [3, 12], territories: null, ownedLocation: [3, 13], acceptedNames: []},
	{name: "India", location: [3, 13], territories: [[3, 11], [3, 12]], ownedLocation: null, acceptedNames: ["india"]},
	{name: "Indonesia", location: [3, 14], territories: null, ownedLocation: null, acceptedNames: ["indonesia"]},
	{name: "Iran", location: [3, 15], territories: null, ownedLocation: null, acceptedNames: ["iran"]},
	{name: "Iraq", location: [3, 16], territories: null, ownedLocation: null, acceptedNames: ["iraq"]},
	{name: "Israel", location: [3, 17], territories: null, ownedLocation: null, acceptedNames: ["israel"]},
	{name: "Japan", location: [3, 18], territories: null, ownedLocation: null, acceptedNames: ["japan"]},
	{name: "Jordan", location: [3, 19], territories: null, ownedLocation: null, acceptedNames: ["jordan"]},
	{name: "Kazakhstan", location: [3, 20], territories: null, ownedLocation: null, acceptedNames: ["kazakhstan"]},
	{name: "Kuwait", location: [3, 21], territories: null, ownedLocation: null, acceptedNames: ["kuwait"]},
	{name: "Kyrgyzstan", location: [3, 22], territories: null, ownedLocation: null, acceptedNames: ["kyrgyzstan"]},
	{name: "Laos", location: [3, 23], territories: null, ownedLocation: null, acceptedNames: ["laos"]},
	{name: "Lebanon", location: [3, 24], territories: null, ownedLocation: null, acceptedNames: ["lebanon"]},
	{name: "Malaysia", location: [3, 25], territories: null, ownedLocation: null, acceptedNames: ["malaysia"]},
	{name: "Maldives", location: [3, 26], territories: null, ownedLocation: null, acceptedNames: ["maldives"]},
	{name: "Mongolia", location: [3, 27], territories: null, ownedLocation: null, acceptedNames: ["mongolia"]},
	{name: "Myanmar", location: [3, 28], territories: null, ownedLocation: null, acceptedNames: ["burma", "myanmar"]},
	{name: "Nepal", location: [3, 29], territories: null, ownedLocation: null, acceptedNames: ["nepal"]},
	{name: "North Korea", location: [3, 30], territories: null, ownedLocation: null, acceptedNames: ["rok", "northkorea"]},
	{name: "Oman", location: [3, 31], territories: null, ownedLocation: null, acceptedNames: ["oman"]},
	{name: "Pakistan", location: [3, 32], territories: [[3, 35]], ownedLocation: null, acceptedNames: ["pakistan"]},
	{name: "Palestine", location: [3, 33], territories: null, ownedLocation: null, acceptedNames: ["palestine"]},
	{name: "Philippines", location: [3, 34], territories: null, ownedLocation: null, acceptedNames: ["philippines"]},
	{name: "Kashmir (PK)", location: [3, 35], territories: null, ownedLocation: [3, 32], acceptedNames: []},
	{name: "Qatar", location: [3, 36], territories: null, ownedLocation: null, acceptedNames: ["qatar"]},
	{name: "Russia", location: [3, 37], territories: null, ownedLocation: null, acceptedNames: ["russia"]},
	{name: "Saudi Arabia", location: [3, 38], territories: null, ownedLocation: null, acceptedNames: ["ksa", "saudiarabia"]},
	{name: "South Korea", location: [3, 39], territories: null, ownedLocation: null, acceptedNames: ["dprk", "southkorea"]},
	{name: "Sri Lanka", location: [3, 40], territories: null, ownedLocation: null, acceptedNames: ["srilanka"]},
	{name: "Syrian Arab Republic", location: [3, 41], territories: null, ownedLocation: null, acceptedNames: ["syria", "syrianarabrepublic"]},
	{name: "Taiwan", location: [3, 42], territories: null, ownedLocation: null, acceptedNames: ["roc", "taiwan"]},
	{name: "Tajikistan", location: [3, 43], territories: null, ownedLocation: null, acceptedNames: ["tajikistan"]},
	{name: "Thailand", location: [3, 44], territories: null, ownedLocation: null, acceptedNames: ["thailand"]},
	{name: "Turkey", location: [3, 45], territories: null, ownedLocation: null, acceptedNames: ["turkey"]},
	{name: "Turkmenistan", location: [3, 46], territories: null, ownedLocation: null, acceptedNames: ["turkmenistan"]},
	{name: "Chagos Archipelago (UK)", location: [3, 47], territories: null, ownedLocation: [5, 44], acceptedNames: []},
	{name: "United Arab Emirates", location: [3, 48], territories: null, ownedLocation: null, acceptedNames: ["uae", "unitedarabemirates"]},
	{name: "Uzbekistan", location: [3, 49], territories: null, ownedLocation: null, acceptedNames: ["uzbekistan"]},
	{name: "Vietnam", location: [3, 50], territories: null, ownedLocation: null, acceptedNames: ["vietnam"]},
	{name: "Yemen", location: [3, 51], territories: null, ownedLocation: null, acceptedNames: ["yemen"]},
	{name: "Australia", location: [4, 0], territories: null, ownedLocation: null, acceptedNames: ["australia"]},
	{name: "Fiji", location: [4, 1], territories: null, ownedLocation: null, acceptedNames: ["fiji"]},
	{name: "French Polynesia (FR)", location: [4, 2], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "New Caledonia (FR)", location: [4, 3], territories: null, ownedLocation: [5, 15], acceptedNames: []},
	{name: "Marshall Islands", location: [4, 4], territories: null, ownedLocation: null, acceptedNames: ["marshallislands"]},
	{name: "Micronesia", location: [4, 5], territories: null, ownedLocation: null, acceptedNames: ["fsm", "micronesia"]},
	{name: "Nauru", location: [4, 6], territories: null, ownedLocation: null, acceptedNames: ["nauru"]},
	{name: "New Zealand", location: [4, 7], territories: [[4, 8], [4, 9]], ownedLocation: null, acceptedNames: ["nz", "newzealand"]},
	{name: "Cook Islands (NZ)", location: [4, 8], territories: null, ownedLocation: [4, 7], acceptedNames: []},
	{name: "Tokelau (NZ)", location: [4, 9], territories: null, ownedLocation: [4, 7], acceptedNames: []},
	{name: "Palau", location: [4, 10], territories: null, ownedLocation: null, acceptedNames: ["palau"]},
	{name: "Papua New Guinea", location: [4, 11], territories: null, ownedLocation: null, acceptedNames: ["png", "papuanewguinea"]},
	{name: "Samoa", location: [4, 12], territories: null, ownedLocation: null, acceptedNames: ["samoa"]},
	{name: "Solomon Islands", location: [4, 13], territories: null, ownedLocation: null, acceptedNames: ["solomonislands"]},
	{name: "Tonga", location: [4, 14], territories: null, ownedLocation: null, acceptedNames: ["tonga"]},
	{name: "Tuvalu", location: [4, 15], territories: null, ownedLocation: null, acceptedNames: ["tuvalu"]},
	{name: "Guam (US)", location: [4, 16], territories: null, ownedLocation: [1, 45], acceptedNames: []},
	{name: "Northern Mariana Islands (US)", location: [4, 17], territories: null, ownedLocation: [1, 45], acceptedNames: []},
	{name: "Vanuatu", location: [4, 18], territories: null, ownedLocation: null, acceptedNames: ["vanuatu"]},
	{name: "Albany", location: [5, 0], territories: null, ownedLocation: null, acceptedNames: ["albany", "albania"]},
	{name: "Andorra", location: [5, 1], territories: null, ownedLocation: null, acceptedNames: ["andorra"]},
	{name: "Austria", location: [5, 2], territories: null, ownedLocation: null, acceptedNames: ["austria"]},
	{name: "Belarus", location: [5, 3], territories: null, ownedLocation: null, acceptedNames: ["belarus"]},
	{name: "Belgium", location: [5, 4], territories: null, ownedLocation: null, acceptedNames: ["belgium"]},
	{name: "Bosnia and Herzegovina", location: [5, 5], territories: null, ownedLocation: null, acceptedNames: ["bosnia", "bosniaandherzegovina"]},
	{name: "Bulgaria", location: [5, 6], territories: null, ownedLocation: null, acceptedNames: ["bulgaria"]},
	{name: "Crimea (UKR)", location: [5, 7], territories: null, ownedLocation: [5, 43], acceptedNames: []},
	{name: "Croatia", location: [5, 8], territories: null, ownedLocation: null, acceptedNames: ["croatia"]},
	{name: "Cyprus", location: [5, 9], territories: null, ownedLocation: null, acceptedNames: ["cyprus"]},
	{name: "Czech Republic", location: [5, 10], territories: null, ownedLocation: null, acceptedNames: ["czechia", "czechrepublic"]},
	{name: "Denmark", location: [5, 11], territories: [[1, 12], [5, 12]], ownedLocation: null, acceptedNames: ["denmark"]},
	{name: "Faroe Islands (DK)", location: [5, 12], territories: null, ownedLocation: [5, 11], acceptedNames: []},
	{name: "Estonia", location: [5, 13], territories: null, ownedLocation: null, acceptedNames: ["estonia"]},
	{name: "Finland", location: [5, 14], territories: null, ownedLocation: null, acceptedNames: ["finland"]},
	{name: "France", location: [5, 15], territories: [[0, 19], [0, 20], [1, 16], [1, 17], [1, 18], [4, 2], [4, 3]], ownedLocation: null, acceptedNames: ["france"]},
	{name: "Germany", location: [5, 16], territories: null, ownedLocation: null, acceptedNames: ["germany"]},
	{name: "Greece", location: [5, 17], territories: null, ownedLocation: null, acceptedNames: ["greece"]},
	{name: "Hungary", location: [5, 18], territories: null, ownedLocation: null, acceptedNames: ["hungary"]},
	{name: "Iceland", location: [5, 19], territories: null, ownedLocation: null, acceptedNames: ["iceland"]},
	{name: "Ireland", location: [5, 20], territories: null, ownedLocation: null, acceptedNames: ["ireland"]},
	{name: "Italy", location: [5, 21], territories: null, ownedLocation: null, acceptedNames: ["italy"]},
	{name: "Kosovo", location: [5, 22], territories: null, ownedLocation: null, acceptedNames: ["kosovo"]},
	{name: "Latvia", location: [5, 23], territories: null, ownedLocation: null, acceptedNames: ["latvia"]},
	{name: "Liechtenstein", location: [5, 24], territories: null, ownedLocation: null, acceptedNames: ["liechtenstein"]},
	{name: "Lithuania", location: [5, 25], territories: null, ownedLocation: null, acceptedNames: ["lithuania"]},
	{name: "Luxembourg", location: [5, 26], territories: null, ownedLocation: null, acceptedNames: ["luxembourg"]},
	{name: "Macedonia", location: [5, 27], territories: null, ownedLocation: null, acceptedNames: ["macedonia"]},
	{name: "Malta", location: [5, 28], territories: null, ownedLocation: null, acceptedNames: ["malta"]},
	{name: "Netherlands", location: [5, 29], territories: [[1, 27], [1, 28]], ownedLocation: null, acceptedNames: ["netherlands"]},
	{name: "Norway", location: [5, 30], territories: [[5, 31]], ownedLocation: null, acceptedNames: ["norway"]},
	{name: "Svalbard (NW)", location: [5, 31], territories: null, ownedLocation: [5, 30], acceptedNames: []},
	{name: "Poland", location: [5, 32], territories: null, ownedLocation: null, acceptedNames: ["poland"]},
	{name: "Portugal", location: [5, 33], territories: null, ownedLocation: null, acceptedNames: ["portugal"]},
	{name: "Republic of Moldova", location: [5, 34], territories: null, ownedLocation: null, acceptedNames: ["moldova", "republicofmoldova"]},
	{name: "Romania", location: [5, 35], territories: null, ownedLocation: null, acceptedNames: ["romania"]},
	{name: "Serbia", location: [5, 36], territories: null, ownedLocation: null, acceptedNames: ["serbia"]},
	{name: "Montenegro", location: [5, 37], territories: null, ownedLocation: null, acceptedNames: ["montenegro"]},
	{name: "Slovakia", location: [5, 38], territories: null, ownedLocation: null, acceptedNames: ["slovakia"]},
	{name: "Slovenia", location: [5, 39], territories: null, ownedLocation: null, acceptedNames: ["slovenia"]},
	{name: "Spain", location: [5, 40], territories: null, ownedLocation: null, acceptedNames: ["spain"]},
	{name: "Sweden", location: [5, 41], territories: null, ownedLocation: null, acceptedNames: ["sweden"]},
	{name: "Switzerland", location: [5, 42], territories: null, ownedLocation: null, acceptedNames: ["switzerland"]},
	{name: "Ukraine", location: [5, 43], territories: [[5, 7]], ownedLocation: null, acceptedNames: ["ukraine"]},
	{name: "United Kingdom", location: [5, 44], territories: [[1, 44], [1, 43], [1, 42], [1, 41], [1, 40], [1, 39], [2, 1], [2, 2], [3, 47]], ownedLocation: null, acceptedNames: ["uk", "unitedkingdom"]}];